//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Clients { get; set; }
        public DbSet<Sasiu> Sasius { get; set; }
        public DbSet<Mecanic> Mecanics { get; set; }
        public DbSet<Auto> Autoes { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<Imagine> Imagines { get; set; }
        public DbSet<Operatie> Operaties { get; set; }
        public DbSet<Comanda> Comandas { get; set; }
        public DbSet<DetaliuComanda> DetaliuComandas { get; set; }
    }
}
