//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Material
    {
        [DataMember]
        public int MaterialId { get; set; }
        [DataMember]
        public string Denumire { get; set; }
        [DataMember]
        public decimal Cantitate { get; set; }
        [DataMember]
        public decimal Pret { get; set; }
        [DataMember]
        public System.DateTime DataAprovizionare { get; set; }
    }
}
