//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWinForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumarAutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Sasiu SasiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieSasiuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId {
            get {
                return this.AutoIdField;
            }
            set {
                if ((this.AutoIdField.Equals(value) != true)) {
                    this.AutoIdField = value;
                    this.RaisePropertyChanged("AutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto {
            get {
                return this.NumarAutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumarAutoField, value) != true)) {
                    this.NumarAutoField = value;
                    this.RaisePropertyChanged("NumarAuto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Sasiu Sasiu {
            get {
                return this.SasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.SasiuField, value) != true)) {
                    this.SasiuField = value;
                    this.RaisePropertyChanged("Sasiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu {
            get {
                return this.SerieSasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieSasiuField, value) != true)) {
                    this.SerieSasiuField = value;
                    this.RaisePropertyChanged("SerieSasiu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JudetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalitateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet {
            get {
                return this.JudetField;
            }
            set {
                if ((object.ReferenceEquals(this.JudetField, value) != true)) {
                    this.JudetField = value;
                    this.RaisePropertyChanged("Judet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate {
            get {
                return this.LocalitateField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalitateField, value) != true)) {
                    this.LocalitateField = value;
                    this.RaisePropertyChanged("Localitate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((this.TelefonField.Equals(value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Sasiu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodSasiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SasiuIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu {
            get {
                return this.CodSasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSasiuField, value) != true)) {
                    this.CodSasiuField = value;
                    this.RaisePropertyChanged("CodSasiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId {
            get {
                return this.SasiuIdField;
            }
            set {
                if ((this.SasiuIdField.Equals(value) != true)) {
                    this.SasiuIdField = value;
                    this.RaisePropertyChanged("SasiuId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Comanda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Auto AutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComandaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DAtaSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataFinalizareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataProgramareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.DetaliuComanda DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KmBordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Operatie[] OperatiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.StareComanda StareComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValoarePieseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Auto Auto {
            get {
                return this.AutoField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoField, value) != true)) {
                    this.AutoField = value;
                    this.RaisePropertyChanged("Auto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaID {
            get {
                return this.ComandaIDField;
            }
            set {
                if ((this.ComandaIDField.Equals(value) != true)) {
                    this.ComandaIDField = value;
                    this.RaisePropertyChanged("ComandaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DAtaSystem {
            get {
                return this.DAtaSystemField;
            }
            set {
                if ((this.DAtaSystemField.Equals(value) != true)) {
                    this.DAtaSystemField = value;
                    this.RaisePropertyChanged("DAtaSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFinalizare {
            get {
                return this.DataFinalizareField;
            }
            set {
                if ((this.DataFinalizareField.Equals(value) != true)) {
                    this.DataFinalizareField = value;
                    this.RaisePropertyChanged("DataFinalizare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProgramare {
            get {
                return this.DataProgramareField;
            }
            set {
                if ((this.DataProgramareField.Equals(value) != true)) {
                    this.DataProgramareField = value;
                    this.RaisePropertyChanged("DataProgramare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.DetaliuComanda DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KmBord {
            get {
                return this.KmBordField;
            }
            set {
                if ((this.KmBordField.Equals(value) != true)) {
                    this.KmBordField = value;
                    this.RaisePropertyChanged("KmBord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Operatie[] Operaties {
            get {
                return this.OperatiesField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatiesField, value) != true)) {
                    this.OperatiesField = value;
                    this.RaisePropertyChanged("Operaties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.StareComanda StareComanda {
            get {
                return this.StareComandaField;
            }
            set {
                if ((this.StareComandaField.Equals(value) != true)) {
                    this.StareComandaField = value;
                    this.RaisePropertyChanged("StareComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValoarePiese {
            get {
                return this.ValoarePieseField;
            }
            set {
                if ((this.ValoarePieseField.Equals(value) != true)) {
                    this.ValoarePieseField = value;
                    this.RaisePropertyChanged("ValoarePiese");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliuComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class DetaliuComanda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Comanda ComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Imagine[] ImaginesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Material[] MaterialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.Mecanic[] MecanicsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Comanda Comanda {
            get {
                return this.ComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandaField, value) != true)) {
                    this.ComandaField = value;
                    this.RaisePropertyChanged("Comanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Imagine[] Imagines {
            get {
                return this.ImaginesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImaginesField, value) != true)) {
                    this.ImaginesField = value;
                    this.RaisePropertyChanged("Imagines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Material[] Materials {
            get {
                return this.MaterialsField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialsField, value) != true)) {
                    this.MaterialsField = value;
                    this.RaisePropertyChanged("Materials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.Mecanic[] Mecanics {
            get {
                return this.MecanicsField;
            }
            set {
                if ((object.ReferenceEquals(this.MecanicsField, value) != true)) {
                    this.MecanicsField = value;
                    this.RaisePropertyChanged("Mecanics");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Operatie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperatieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TimpExecutieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatieId {
            get {
                return this.OperatieIdField;
            }
            set {
                if ((this.OperatieIdField.Equals(value) != true)) {
                    this.OperatieIdField = value;
                    this.RaisePropertyChanged("OperatieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimpExecutie {
            get {
                return this.TimpExecutieField;
            }
            set {
                if ((this.TimpExecutieField.Equals(value) != true)) {
                    this.TimpExecutieField = value;
                    this.RaisePropertyChanged("TimpExecutie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="StareComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public enum StareComanda : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Asteptare = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Executata = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refuz = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Imagine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarWinForm.ServiceReference1.DetaliuComanda DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImagineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitluField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarWinForm.ServiceReference1.DetaliuComanda DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImagineId {
            get {
                return this.ImagineIdField;
            }
            set {
                if ((this.ImagineIdField.Equals(value) != true)) {
                    this.ImagineIdField = value;
                    this.RaisePropertyChanged("ImagineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu {
            get {
                return this.TitluField;
            }
            set {
                if ((object.ReferenceEquals(this.TitluField, value) != true)) {
                    this.TitluField = value;
                    this.RaisePropertyChanged("Titlu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantitateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataAprovizionareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaterialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PretField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantitate {
            get {
                return this.CantitateField;
            }
            set {
                if ((this.CantitateField.Equals(value) != true)) {
                    this.CantitateField = value;
                    this.RaisePropertyChanged("Cantitate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAprovizionare {
            get {
                return this.DataAprovizionareField;
            }
            set {
                if ((this.DataAprovizionareField.Equals(value) != true)) {
                    this.DataAprovizionareField = value;
                    this.RaisePropertyChanged("DataAprovizionare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaterialId {
            get {
                return this.MaterialIdField;
            }
            set {
                if ((this.MaterialIdField.Equals(value) != true)) {
                    this.MaterialIdField = value;
                    this.RaisePropertyChanged("MaterialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pret {
            get {
                return this.PretField;
            }
            set {
                if ((this.PretField.Equals(value) != true)) {
                    this.PretField = value;
                    this.RaisePropertyChanged("Pret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Mecanic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MecanicIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MecanicId {
            get {
                return this.MecanicIdField;
            }
            set {
                if ((this.MecanicIdField.Equals(value) != true)) {
                    this.MecanicIdField = value;
                    this.RaisePropertyChanged("MecanicId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.InterfaceControll")]
    public interface InterfaceControll {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/AddAuto", ReplyAction="http://tempuri.org/InterfaceAuto/AddAutoResponse")]
        void AddAuto(CarWinForm.ServiceReference1.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/AddAuto", ReplyAction="http://tempuri.org/InterfaceAuto/AddAutoResponse")]
        System.Threading.Tasks.Task AddAutoAsync(CarWinForm.ServiceReference1.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/DeleteAuto", ReplyAction="http://tempuri.org/InterfaceAuto/DeleteAutoResponse")]
        void DeleteAuto(CarWinForm.ServiceReference1.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/DeleteAuto", ReplyAction="http://tempuri.org/InterfaceAuto/DeleteAutoResponse")]
        System.Threading.Tasks.Task DeleteAutoAsync(CarWinForm.ServiceReference1.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAuto", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoResponse")]
        CarWinForm.ServiceReference1.Auto GetAuto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAuto", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Auto> GetAutoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoByClient", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoByClientResponse")]
        CarWinForm.ServiceReference1.Auto[] GetAutoByClient(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoByClient", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoByClientResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Auto[]> GetAutoByClientAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAllAuto", ReplyAction="http://tempuri.org/InterfaceAuto/GetAllAutoResponse")]
        CarWinForm.ServiceReference1.Auto[] GetAllAuto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAllAuto", ReplyAction="http://tempuri.org/InterfaceAuto/GetAllAutoResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Auto[]> GetAllAutoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/InsertAuto", ReplyAction="http://tempuri.org/InterfaceAuto/InsertAutoResponse")]
        void InsertAuto(CarWinForm.ServiceReference1.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/InsertAuto", ReplyAction="http://tempuri.org/InterfaceAuto/InsertAutoResponse")]
        System.Threading.Tasks.Task InsertAutoAsync(CarWinForm.ServiceReference1.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/UpdateAuto", ReplyAction="http://tempuri.org/InterfaceAuto/UpdateAutoResponse")]
        void UpdateAuto(CarWinForm.ServiceReference1.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/UpdateAuto", ReplyAction="http://tempuri.org/InterfaceAuto/UpdateAutoResponse")]
        System.Threading.Tasks.Task UpdateAutoAsync(CarWinForm.ServiceReference1.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/AddClient", ReplyAction="http://tempuri.org/InterfaceClient/AddClientResponse")]
        void AddClient(CarWinForm.ServiceReference1.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/AddClient", ReplyAction="http://tempuri.org/InterfaceClient/AddClientResponse")]
        System.Threading.Tasks.Task AddClientAsync(CarWinForm.ServiceReference1.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/DeleteClient", ReplyAction="http://tempuri.org/InterfaceClient/DeleteClientResponse")]
        void DeleteClient(CarWinForm.ServiceReference1.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/DeleteClient", ReplyAction="http://tempuri.org/InterfaceClient/DeleteClientResponse")]
        System.Threading.Tasks.Task DeleteClientAsync(CarWinForm.ServiceReference1.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClient", ReplyAction="http://tempuri.org/InterfaceClient/GetClientResponse")]
        CarWinForm.ServiceReference1.Client GetClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClient", ReplyAction="http://tempuri.org/InterfaceClient/GetClientResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Client> GetClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetAllClient", ReplyAction="http://tempuri.org/InterfaceClient/GetAllClientResponse")]
        CarWinForm.ServiceReference1.Client[] GetAllClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetAllClient", ReplyAction="http://tempuri.org/InterfaceClient/GetAllClientResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Client[]> GetAllClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/InsertClient", ReplyAction="http://tempuri.org/InterfaceClient/InsertClientResponse")]
        void InsertClient(CarWinForm.ServiceReference1.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/InsertClient", ReplyAction="http://tempuri.org/InterfaceClient/InsertClientResponse")]
        System.Threading.Tasks.Task InsertClientAsync(CarWinForm.ServiceReference1.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/UpdateClient", ReplyAction="http://tempuri.org/InterfaceClient/UpdateClientResponse")]
        void UpdateClient(CarWinForm.ServiceReference1.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/UpdateClient", ReplyAction="http://tempuri.org/InterfaceClient/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(CarWinForm.ServiceReference1.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComanda", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaResponse")]
        void AddComanda(CarWinForm.ServiceReference1.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComanda", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaResponse")]
        System.Threading.Tasks.Task AddComandaAsync(CarWinForm.ServiceReference1.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/DeleteComanda", ReplyAction="http://tempuri.org/InterfaceComanda/DeleteComandaResponse")]
        void DeleteComanda(CarWinForm.ServiceReference1.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/DeleteComanda", ReplyAction="http://tempuri.org/InterfaceComanda/DeleteComandaResponse")]
        System.Threading.Tasks.Task DeleteComandaAsync(CarWinForm.ServiceReference1.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComanda", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandaResponse")]
        CarWinForm.ServiceReference1.Comanda GetComanda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComanda", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandaResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Comanda> GetComandaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetAllComanda", ReplyAction="http://tempuri.org/InterfaceComanda/GetAllComandaResponse")]
        CarWinForm.ServiceReference1.Comanda[] GetAllComanda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetAllComanda", ReplyAction="http://tempuri.org/InterfaceComanda/GetAllComandaResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Comanda[]> GetAllComandaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/InsertComanda", ReplyAction="http://tempuri.org/InterfaceComanda/InsertComandaResponse")]
        void InsertComanda(CarWinForm.ServiceReference1.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/InsertComanda", ReplyAction="http://tempuri.org/InterfaceComanda/InsertComandaResponse")]
        System.Threading.Tasks.Task InsertComandaAsync(CarWinForm.ServiceReference1.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/UpdateComanda", ReplyAction="http://tempuri.org/InterfaceComanda/UpdateComandaResponse")]
        void UpdateComanda(CarWinForm.ServiceReference1.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/UpdateComanda", ReplyAction="http://tempuri.org/InterfaceComanda/UpdateComandaResponse")]
        System.Threading.Tasks.Task UpdateComandaAsync(CarWinForm.ServiceReference1.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/AddDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/AddDetaliuComandaResponse")]
        void AddDetaliuComanda(CarWinForm.ServiceReference1.DetaliuComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/AddDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/AddDetaliuComandaResponse")]
        System.Threading.Tasks.Task AddDetaliuComandaAsync(CarWinForm.ServiceReference1.DetaliuComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/DeleteDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/DeleteDetaliuComandaResponse")]
        void DeleteDetaliuComanda(CarWinForm.ServiceReference1.DetaliuComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/DeleteDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/DeleteDetaliuComandaResponse")]
        System.Threading.Tasks.Task DeleteDetaliuComandaAsync(CarWinForm.ServiceReference1.DetaliuComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/GetDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/GetDetaliuComandaResponse")]
        CarWinForm.ServiceReference1.DetaliuComanda GetDetaliuComanda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/GetDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/GetDetaliuComandaResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.DetaliuComanda> GetDetaliuComandaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/GetAllDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/GetAllDetaliuComandaResponse")]
        CarWinForm.ServiceReference1.DetaliuComanda[] GetAllDetaliuComanda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/GetAllDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/GetAllDetaliuComandaResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.DetaliuComanda[]> GetAllDetaliuComandaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/InsertDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/InsertDetaliuComandaResponse")]
        void InsertDetaliuComanda(CarWinForm.ServiceReference1.DetaliuComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/InsertDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/InsertDetaliuComandaResponse")]
        System.Threading.Tasks.Task InsertDetaliuComandaAsync(CarWinForm.ServiceReference1.DetaliuComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/UpdateDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/UpdateDetaliuComandaResponse")]
        void UpdateDetaliuComanda(CarWinForm.ServiceReference1.DetaliuComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/UpdateDetaliuComanda", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/UpdateDetaliuComandaResponse")]
        System.Threading.Tasks.Task UpdateDetaliuComandaAsync(CarWinForm.ServiceReference1.DetaliuComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/AddImagine", ReplyAction="http://tempuri.org/InterfaceImagine/AddImagineResponse")]
        void AddImagine(CarWinForm.ServiceReference1.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/AddImagine", ReplyAction="http://tempuri.org/InterfaceImagine/AddImagineResponse")]
        System.Threading.Tasks.Task AddImagineAsync(CarWinForm.ServiceReference1.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/DeleteImagine", ReplyAction="http://tempuri.org/InterfaceImagine/DeleteImagineResponse")]
        void DeleteImagine(CarWinForm.ServiceReference1.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/DeleteImagine", ReplyAction="http://tempuri.org/InterfaceImagine/DeleteImagineResponse")]
        System.Threading.Tasks.Task DeleteImagineAsync(CarWinForm.ServiceReference1.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/GetImagine", ReplyAction="http://tempuri.org/InterfaceImagine/GetImagineResponse")]
        CarWinForm.ServiceReference1.Imagine GetImagine(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/GetImagine", ReplyAction="http://tempuri.org/InterfaceImagine/GetImagineResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Imagine> GetImagineAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/GetAllImagine", ReplyAction="http://tempuri.org/InterfaceImagine/GetAllImagineResponse")]
        CarWinForm.ServiceReference1.Imagine[] GetAllImagine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/GetAllImagine", ReplyAction="http://tempuri.org/InterfaceImagine/GetAllImagineResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Imagine[]> GetAllImagineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/InsertImagine", ReplyAction="http://tempuri.org/InterfaceImagine/InsertImagineResponse")]
        void InsertImagine(CarWinForm.ServiceReference1.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/InsertImagine", ReplyAction="http://tempuri.org/InterfaceImagine/InsertImagineResponse")]
        System.Threading.Tasks.Task InsertImagineAsync(CarWinForm.ServiceReference1.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/UpdateImagine", ReplyAction="http://tempuri.org/InterfaceImagine/UpdateImagineResponse")]
        void UpdateImagine(CarWinForm.ServiceReference1.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/UpdateImagine", ReplyAction="http://tempuri.org/InterfaceImagine/UpdateImagineResponse")]
        System.Threading.Tasks.Task UpdateImagineAsync(CarWinForm.ServiceReference1.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/AddMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/AddMaterialResponse")]
        void AddMaterial(CarWinForm.ServiceReference1.Material entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/AddMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/AddMaterialResponse")]
        System.Threading.Tasks.Task AddMaterialAsync(CarWinForm.ServiceReference1.Material entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/DeleteMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/DeleteMaterialResponse")]
        void DeleteMaterial(CarWinForm.ServiceReference1.Material entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/DeleteMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/DeleteMaterialResponse")]
        System.Threading.Tasks.Task DeleteMaterialAsync(CarWinForm.ServiceReference1.Material entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/GetMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/GetMaterialResponse")]
        CarWinForm.ServiceReference1.Material GetMaterial(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/GetMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/GetMaterialResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Material> GetMaterialAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/GetAllMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/GetAllMaterialResponse")]
        CarWinForm.ServiceReference1.Material[] GetAllMaterial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/GetAllMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/GetAllMaterialResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Material[]> GetAllMaterialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/InsertMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/InsertMaterialResponse")]
        void InsertMaterial(CarWinForm.ServiceReference1.Material entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/InsertMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/InsertMaterialResponse")]
        System.Threading.Tasks.Task InsertMaterialAsync(CarWinForm.ServiceReference1.Material entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/UpdateMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/UpdateMaterialResponse")]
        void UpdateMaterial(CarWinForm.ServiceReference1.Material entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/UpdateMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/UpdateMaterialResponse")]
        System.Threading.Tasks.Task UpdateMaterialAsync(CarWinForm.ServiceReference1.Material entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/AddMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/AddMecanicResponse")]
        void AddMecanic(CarWinForm.ServiceReference1.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/AddMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/AddMecanicResponse")]
        System.Threading.Tasks.Task AddMecanicAsync(CarWinForm.ServiceReference1.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/DeleteMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/DeleteMecanicResponse")]
        void DeleteMecanic(CarWinForm.ServiceReference1.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/DeleteMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/DeleteMecanicResponse")]
        System.Threading.Tasks.Task DeleteMecanicAsync(CarWinForm.ServiceReference1.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/GetMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/GetMecanicResponse")]
        CarWinForm.ServiceReference1.Mecanic GetMecanic(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/GetMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/GetMecanicResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Mecanic> GetMecanicAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/GetAllMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/GetAllMecanicResponse")]
        CarWinForm.ServiceReference1.Mecanic[] GetAllMecanic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/GetAllMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/GetAllMecanicResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Mecanic[]> GetAllMecanicAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/InsertMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/InsertMecanicResponse")]
        void InsertMecanic(CarWinForm.ServiceReference1.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/InsertMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/InsertMecanicResponse")]
        System.Threading.Tasks.Task InsertMecanicAsync(CarWinForm.ServiceReference1.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/UpdateMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/UpdateMecanicResponse")]
        void UpdateMecanic(CarWinForm.ServiceReference1.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/UpdateMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/UpdateMecanicResponse")]
        System.Threading.Tasks.Task UpdateMecanicAsync(CarWinForm.ServiceReference1.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/AddOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/AddOperatieResponse")]
        void AddOperatie(CarWinForm.ServiceReference1.Operatie entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/AddOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/AddOperatieResponse")]
        System.Threading.Tasks.Task AddOperatieAsync(CarWinForm.ServiceReference1.Operatie entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/DeleteOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/DeleteOperatieResponse")]
        void DeleteOperatie(CarWinForm.ServiceReference1.Operatie entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/DeleteOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/DeleteOperatieResponse")]
        System.Threading.Tasks.Task DeleteOperatieAsync(CarWinForm.ServiceReference1.Operatie entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/GetOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/GetOperatieResponse")]
        CarWinForm.ServiceReference1.Operatie GetOperatie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/GetOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/GetOperatieResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Operatie> GetOperatieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/GetAllOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/GetAllOperatieResponse")]
        CarWinForm.ServiceReference1.Operatie[] GetAllOperatie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/GetAllOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/GetAllOperatieResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Operatie[]> GetAllOperatieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/InsertOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/InsertOperatieResponse")]
        void InsertOperatie(CarWinForm.ServiceReference1.Operatie entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/InsertOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/InsertOperatieResponse")]
        System.Threading.Tasks.Task InsertOperatieAsync(CarWinForm.ServiceReference1.Operatie entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/UpdateOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/UpdateOperatieResponse")]
        void UpdateOperatie(CarWinForm.ServiceReference1.Operatie entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/UpdateOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/UpdateOperatieResponse")]
        System.Threading.Tasks.Task UpdateOperatieAsync(CarWinForm.ServiceReference1.Operatie entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/AddSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/AddSasiuResponse")]
        void AddSasiu(CarWinForm.ServiceReference1.Sasiu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/AddSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/AddSasiuResponse")]
        System.Threading.Tasks.Task AddSasiuAsync(CarWinForm.ServiceReference1.Sasiu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/DeleteSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/DeleteSasiuResponse")]
        void DeleteSasiu(CarWinForm.ServiceReference1.Sasiu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/DeleteSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/DeleteSasiuResponse")]
        System.Threading.Tasks.Task DeleteSasiuAsync(CarWinForm.ServiceReference1.Sasiu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuResponse")]
        CarWinForm.ServiceReference1.Sasiu GetSasiu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Sasiu> GetSasiuAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetAllSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/GetAllSasiuResponse")]
        CarWinForm.ServiceReference1.Sasiu[] GetAllSasiu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetAllSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/GetAllSasiuResponse")]
        System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Sasiu[]> GetAllSasiuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/InsertSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/InsertSasiuResponse")]
        void InsertSasiu(CarWinForm.ServiceReference1.Sasiu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/InsertSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/InsertSasiuResponse")]
        System.Threading.Tasks.Task InsertSasiuAsync(CarWinForm.ServiceReference1.Sasiu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/UpdateSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/UpdateSasiuResponse")]
        void UpdateSasiu(CarWinForm.ServiceReference1.Sasiu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/UpdateSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/UpdateSasiuResponse")]
        System.Threading.Tasks.Task UpdateSasiuAsync(CarWinForm.ServiceReference1.Sasiu entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceControllChannel : CarWinForm.ServiceReference1.InterfaceControll, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceControllClient : System.ServiceModel.ClientBase<CarWinForm.ServiceReference1.InterfaceControll>, CarWinForm.ServiceReference1.InterfaceControll {
        
        public InterfaceControllClient() {
        }
        
        public InterfaceControllClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceControllClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceControllClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceControllClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddAuto(CarWinForm.ServiceReference1.Auto entity) {
            base.Channel.AddAuto(entity);
        }
        
        public System.Threading.Tasks.Task AddAutoAsync(CarWinForm.ServiceReference1.Auto entity) {
            return base.Channel.AddAutoAsync(entity);
        }
        
        public void DeleteAuto(CarWinForm.ServiceReference1.Auto entity) {
            base.Channel.DeleteAuto(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAutoAsync(CarWinForm.ServiceReference1.Auto entity) {
            return base.Channel.DeleteAutoAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.Auto GetAuto(int id) {
            return base.Channel.GetAuto(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Auto> GetAutoAsync(int id) {
            return base.Channel.GetAutoAsync(id);
        }
        
        public CarWinForm.ServiceReference1.Auto[] GetAutoByClient(int clientId) {
            return base.Channel.GetAutoByClient(clientId);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Auto[]> GetAutoByClientAsync(int clientId) {
            return base.Channel.GetAutoByClientAsync(clientId);
        }
        
        public CarWinForm.ServiceReference1.Auto[] GetAllAuto() {
            return base.Channel.GetAllAuto();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Auto[]> GetAllAutoAsync() {
            return base.Channel.GetAllAutoAsync();
        }
        
        public void InsertAuto(CarWinForm.ServiceReference1.Auto entity) {
            base.Channel.InsertAuto(entity);
        }
        
        public System.Threading.Tasks.Task InsertAutoAsync(CarWinForm.ServiceReference1.Auto entity) {
            return base.Channel.InsertAutoAsync(entity);
        }
        
        public void UpdateAuto(CarWinForm.ServiceReference1.Auto entity) {
            base.Channel.UpdateAuto(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAutoAsync(CarWinForm.ServiceReference1.Auto entity) {
            return base.Channel.UpdateAutoAsync(entity);
        }
        
        public void AddClient(CarWinForm.ServiceReference1.Client entity) {
            base.Channel.AddClient(entity);
        }
        
        public System.Threading.Tasks.Task AddClientAsync(CarWinForm.ServiceReference1.Client entity) {
            return base.Channel.AddClientAsync(entity);
        }
        
        public void DeleteClient(CarWinForm.ServiceReference1.Client entity) {
            base.Channel.DeleteClient(entity);
        }
        
        public System.Threading.Tasks.Task DeleteClientAsync(CarWinForm.ServiceReference1.Client entity) {
            return base.Channel.DeleteClientAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.Client GetClient(int id) {
            return base.Channel.GetClient(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Client> GetClientAsync(int id) {
            return base.Channel.GetClientAsync(id);
        }
        
        public CarWinForm.ServiceReference1.Client[] GetAllClient() {
            return base.Channel.GetAllClient();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Client[]> GetAllClientAsync() {
            return base.Channel.GetAllClientAsync();
        }
        
        public void InsertClient(CarWinForm.ServiceReference1.Client entity) {
            base.Channel.InsertClient(entity);
        }
        
        public System.Threading.Tasks.Task InsertClientAsync(CarWinForm.ServiceReference1.Client entity) {
            return base.Channel.InsertClientAsync(entity);
        }
        
        public void UpdateClient(CarWinForm.ServiceReference1.Client entity) {
            base.Channel.UpdateClient(entity);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(CarWinForm.ServiceReference1.Client entity) {
            return base.Channel.UpdateClientAsync(entity);
        }
        
        public void AddComanda(CarWinForm.ServiceReference1.Comanda entity) {
            base.Channel.AddComanda(entity);
        }
        
        public System.Threading.Tasks.Task AddComandaAsync(CarWinForm.ServiceReference1.Comanda entity) {
            return base.Channel.AddComandaAsync(entity);
        }
        
        public void DeleteComanda(CarWinForm.ServiceReference1.Comanda entity) {
            base.Channel.DeleteComanda(entity);
        }
        
        public System.Threading.Tasks.Task DeleteComandaAsync(CarWinForm.ServiceReference1.Comanda entity) {
            return base.Channel.DeleteComandaAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.Comanda GetComanda(int id) {
            return base.Channel.GetComanda(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Comanda> GetComandaAsync(int id) {
            return base.Channel.GetComandaAsync(id);
        }
        
        public CarWinForm.ServiceReference1.Comanda[] GetAllComanda() {
            return base.Channel.GetAllComanda();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Comanda[]> GetAllComandaAsync() {
            return base.Channel.GetAllComandaAsync();
        }
        
        public void InsertComanda(CarWinForm.ServiceReference1.Comanda entity) {
            base.Channel.InsertComanda(entity);
        }
        
        public System.Threading.Tasks.Task InsertComandaAsync(CarWinForm.ServiceReference1.Comanda entity) {
            return base.Channel.InsertComandaAsync(entity);
        }
        
        public void UpdateComanda(CarWinForm.ServiceReference1.Comanda entity) {
            base.Channel.UpdateComanda(entity);
        }
        
        public System.Threading.Tasks.Task UpdateComandaAsync(CarWinForm.ServiceReference1.Comanda entity) {
            return base.Channel.UpdateComandaAsync(entity);
        }
        
        public void AddDetaliuComanda(CarWinForm.ServiceReference1.DetaliuComanda entity) {
            base.Channel.AddDetaliuComanda(entity);
        }
        
        public System.Threading.Tasks.Task AddDetaliuComandaAsync(CarWinForm.ServiceReference1.DetaliuComanda entity) {
            return base.Channel.AddDetaliuComandaAsync(entity);
        }
        
        public void DeleteDetaliuComanda(CarWinForm.ServiceReference1.DetaliuComanda entity) {
            base.Channel.DeleteDetaliuComanda(entity);
        }
        
        public System.Threading.Tasks.Task DeleteDetaliuComandaAsync(CarWinForm.ServiceReference1.DetaliuComanda entity) {
            return base.Channel.DeleteDetaliuComandaAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.DetaliuComanda GetDetaliuComanda(int id) {
            return base.Channel.GetDetaliuComanda(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.DetaliuComanda> GetDetaliuComandaAsync(int id) {
            return base.Channel.GetDetaliuComandaAsync(id);
        }
        
        public CarWinForm.ServiceReference1.DetaliuComanda[] GetAllDetaliuComanda() {
            return base.Channel.GetAllDetaliuComanda();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.DetaliuComanda[]> GetAllDetaliuComandaAsync() {
            return base.Channel.GetAllDetaliuComandaAsync();
        }
        
        public void InsertDetaliuComanda(CarWinForm.ServiceReference1.DetaliuComanda entity) {
            base.Channel.InsertDetaliuComanda(entity);
        }
        
        public System.Threading.Tasks.Task InsertDetaliuComandaAsync(CarWinForm.ServiceReference1.DetaliuComanda entity) {
            return base.Channel.InsertDetaliuComandaAsync(entity);
        }
        
        public void UpdateDetaliuComanda(CarWinForm.ServiceReference1.DetaliuComanda entity) {
            base.Channel.UpdateDetaliuComanda(entity);
        }
        
        public System.Threading.Tasks.Task UpdateDetaliuComandaAsync(CarWinForm.ServiceReference1.DetaliuComanda entity) {
            return base.Channel.UpdateDetaliuComandaAsync(entity);
        }
        
        public void AddImagine(CarWinForm.ServiceReference1.Imagine entity) {
            base.Channel.AddImagine(entity);
        }
        
        public System.Threading.Tasks.Task AddImagineAsync(CarWinForm.ServiceReference1.Imagine entity) {
            return base.Channel.AddImagineAsync(entity);
        }
        
        public void DeleteImagine(CarWinForm.ServiceReference1.Imagine entity) {
            base.Channel.DeleteImagine(entity);
        }
        
        public System.Threading.Tasks.Task DeleteImagineAsync(CarWinForm.ServiceReference1.Imagine entity) {
            return base.Channel.DeleteImagineAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.Imagine GetImagine(int id) {
            return base.Channel.GetImagine(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Imagine> GetImagineAsync(int id) {
            return base.Channel.GetImagineAsync(id);
        }
        
        public CarWinForm.ServiceReference1.Imagine[] GetAllImagine() {
            return base.Channel.GetAllImagine();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Imagine[]> GetAllImagineAsync() {
            return base.Channel.GetAllImagineAsync();
        }
        
        public void InsertImagine(CarWinForm.ServiceReference1.Imagine entity) {
            base.Channel.InsertImagine(entity);
        }
        
        public System.Threading.Tasks.Task InsertImagineAsync(CarWinForm.ServiceReference1.Imagine entity) {
            return base.Channel.InsertImagineAsync(entity);
        }
        
        public void UpdateImagine(CarWinForm.ServiceReference1.Imagine entity) {
            base.Channel.UpdateImagine(entity);
        }
        
        public System.Threading.Tasks.Task UpdateImagineAsync(CarWinForm.ServiceReference1.Imagine entity) {
            return base.Channel.UpdateImagineAsync(entity);
        }
        
        public void AddMaterial(CarWinForm.ServiceReference1.Material entity) {
            base.Channel.AddMaterial(entity);
        }
        
        public System.Threading.Tasks.Task AddMaterialAsync(CarWinForm.ServiceReference1.Material entity) {
            return base.Channel.AddMaterialAsync(entity);
        }
        
        public void DeleteMaterial(CarWinForm.ServiceReference1.Material entity) {
            base.Channel.DeleteMaterial(entity);
        }
        
        public System.Threading.Tasks.Task DeleteMaterialAsync(CarWinForm.ServiceReference1.Material entity) {
            return base.Channel.DeleteMaterialAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.Material GetMaterial(int id) {
            return base.Channel.GetMaterial(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Material> GetMaterialAsync(int id) {
            return base.Channel.GetMaterialAsync(id);
        }
        
        public CarWinForm.ServiceReference1.Material[] GetAllMaterial() {
            return base.Channel.GetAllMaterial();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Material[]> GetAllMaterialAsync() {
            return base.Channel.GetAllMaterialAsync();
        }
        
        public void InsertMaterial(CarWinForm.ServiceReference1.Material entity) {
            base.Channel.InsertMaterial(entity);
        }
        
        public System.Threading.Tasks.Task InsertMaterialAsync(CarWinForm.ServiceReference1.Material entity) {
            return base.Channel.InsertMaterialAsync(entity);
        }
        
        public void UpdateMaterial(CarWinForm.ServiceReference1.Material entity) {
            base.Channel.UpdateMaterial(entity);
        }
        
        public System.Threading.Tasks.Task UpdateMaterialAsync(CarWinForm.ServiceReference1.Material entity) {
            return base.Channel.UpdateMaterialAsync(entity);
        }
        
        public void AddMecanic(CarWinForm.ServiceReference1.Mecanic entity) {
            base.Channel.AddMecanic(entity);
        }
        
        public System.Threading.Tasks.Task AddMecanicAsync(CarWinForm.ServiceReference1.Mecanic entity) {
            return base.Channel.AddMecanicAsync(entity);
        }
        
        public void DeleteMecanic(CarWinForm.ServiceReference1.Mecanic entity) {
            base.Channel.DeleteMecanic(entity);
        }
        
        public System.Threading.Tasks.Task DeleteMecanicAsync(CarWinForm.ServiceReference1.Mecanic entity) {
            return base.Channel.DeleteMecanicAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.Mecanic GetMecanic(int id) {
            return base.Channel.GetMecanic(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Mecanic> GetMecanicAsync(int id) {
            return base.Channel.GetMecanicAsync(id);
        }
        
        public CarWinForm.ServiceReference1.Mecanic[] GetAllMecanic() {
            return base.Channel.GetAllMecanic();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Mecanic[]> GetAllMecanicAsync() {
            return base.Channel.GetAllMecanicAsync();
        }
        
        public void InsertMecanic(CarWinForm.ServiceReference1.Mecanic entity) {
            base.Channel.InsertMecanic(entity);
        }
        
        public System.Threading.Tasks.Task InsertMecanicAsync(CarWinForm.ServiceReference1.Mecanic entity) {
            return base.Channel.InsertMecanicAsync(entity);
        }
        
        public void UpdateMecanic(CarWinForm.ServiceReference1.Mecanic entity) {
            base.Channel.UpdateMecanic(entity);
        }
        
        public System.Threading.Tasks.Task UpdateMecanicAsync(CarWinForm.ServiceReference1.Mecanic entity) {
            return base.Channel.UpdateMecanicAsync(entity);
        }
        
        public void AddOperatie(CarWinForm.ServiceReference1.Operatie entity) {
            base.Channel.AddOperatie(entity);
        }
        
        public System.Threading.Tasks.Task AddOperatieAsync(CarWinForm.ServiceReference1.Operatie entity) {
            return base.Channel.AddOperatieAsync(entity);
        }
        
        public void DeleteOperatie(CarWinForm.ServiceReference1.Operatie entity) {
            base.Channel.DeleteOperatie(entity);
        }
        
        public System.Threading.Tasks.Task DeleteOperatieAsync(CarWinForm.ServiceReference1.Operatie entity) {
            return base.Channel.DeleteOperatieAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.Operatie GetOperatie(int id) {
            return base.Channel.GetOperatie(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Operatie> GetOperatieAsync(int id) {
            return base.Channel.GetOperatieAsync(id);
        }
        
        public CarWinForm.ServiceReference1.Operatie[] GetAllOperatie() {
            return base.Channel.GetAllOperatie();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Operatie[]> GetAllOperatieAsync() {
            return base.Channel.GetAllOperatieAsync();
        }
        
        public void InsertOperatie(CarWinForm.ServiceReference1.Operatie entity) {
            base.Channel.InsertOperatie(entity);
        }
        
        public System.Threading.Tasks.Task InsertOperatieAsync(CarWinForm.ServiceReference1.Operatie entity) {
            return base.Channel.InsertOperatieAsync(entity);
        }
        
        public void UpdateOperatie(CarWinForm.ServiceReference1.Operatie entity) {
            base.Channel.UpdateOperatie(entity);
        }
        
        public System.Threading.Tasks.Task UpdateOperatieAsync(CarWinForm.ServiceReference1.Operatie entity) {
            return base.Channel.UpdateOperatieAsync(entity);
        }
        
        public void AddSasiu(CarWinForm.ServiceReference1.Sasiu entity) {
            base.Channel.AddSasiu(entity);
        }
        
        public System.Threading.Tasks.Task AddSasiuAsync(CarWinForm.ServiceReference1.Sasiu entity) {
            return base.Channel.AddSasiuAsync(entity);
        }
        
        public void DeleteSasiu(CarWinForm.ServiceReference1.Sasiu entity) {
            base.Channel.DeleteSasiu(entity);
        }
        
        public System.Threading.Tasks.Task DeleteSasiuAsync(CarWinForm.ServiceReference1.Sasiu entity) {
            return base.Channel.DeleteSasiuAsync(entity);
        }
        
        public CarWinForm.ServiceReference1.Sasiu GetSasiu(int id) {
            return base.Channel.GetSasiu(id);
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Sasiu> GetSasiuAsync(int id) {
            return base.Channel.GetSasiuAsync(id);
        }
        
        public CarWinForm.ServiceReference1.Sasiu[] GetAllSasiu() {
            return base.Channel.GetAllSasiu();
        }
        
        public System.Threading.Tasks.Task<CarWinForm.ServiceReference1.Sasiu[]> GetAllSasiuAsync() {
            return base.Channel.GetAllSasiuAsync();
        }
        
        public void InsertSasiu(CarWinForm.ServiceReference1.Sasiu entity) {
            base.Channel.InsertSasiu(entity);
        }
        
        public System.Threading.Tasks.Task InsertSasiuAsync(CarWinForm.ServiceReference1.Sasiu entity) {
            return base.Channel.InsertSasiuAsync(entity);
        }
        
        public void UpdateSasiu(CarWinForm.ServiceReference1.Sasiu entity) {
            base.Channel.UpdateSasiu(entity);
        }
        
        public System.Threading.Tasks.Task UpdateSasiuAsync(CarWinForm.ServiceReference1.Sasiu entity) {
            return base.Channel.UpdateSasiuAsync(entity);
        }
    }
}
